language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 local_dir: dist
 on:
   branch: main