language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 keep_history: true
 github_token: $GITHUB_TOKEN_VUE_TRAVIS
 local_dir: dist
 on:
   branch: main